server:
  port: 8899
spring:
  application:
    name: crudspringtestproject
  config:
    import: classpath:secret-settings.yml
  datasource:
    url: ${POSTGRES_JDBC_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: ${SHOW_SQL}
    properties:
      hibernate:
        default_schema: ${POSTGRES_SCHEMA}
    open-in-view: false
  data:
    rest:
      base-path: /
      return-body-on-create: true